name: Azure Python 3.5
on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.5.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.5.10"
        
    - name: Install 
      run: |
        pip install black
   
    - name: Lint
      run: | 
        black . --check
